name: Terraform Destroy 

on:
  workflow_dispatch:
    inputs: 
      confirmation: 
        description: 'Type "Confirm" to destroy all the terraform infrastructure resources'
        required: true 
        default: '' 

permissions:
  id-token: write
  contents: read
  security-events: write

jobs: 
  destroy: 
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} #get correct the environment <dev or main >
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Configuration the AWS Credential 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::376129850044:role/sontv-github-svc-practices1
          aws-region: ap-northeast-1
          role-session-name: sontv-github-svc-practices1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3 #verify with your end terraform version

      - name: Terraform init
        run: terraform init -backend-config="key=github_ci/infra/${{ github.ref_name }}-provision.tfstate"
      
      - name: Terraform destroy plan 
        if: ${{ inputs.confirmation == 'Confirm' }}
        run: terraform plan -destroy  -var-file=envs/${{ github.ref_name }}.tfvars

      - name: Terraform destroy  
        if: ${{ inputs.confirmation == 'Confirm' }}
        run: terraform  destroy -auto-approve -var-file=envs/${{ github.ref_name }}.tfvars

      - name: Check Confirmation 
        if: github.event.inputs.confirmation != 'Confirm'
        run: | 
          echo "Confirmation not provided. Skipping terraform destroy."  
          exit 1